In [ ]:
pip install pandas

In [1]:
import pandas as pd

In [2]:
data = {'Name': ['Alice', 'Bob'], 'Age': [25, 30]}
df = pd.DataFrame(data)

In [3]:
df

    Name  Age
0  Alice   25
1    Bob   30

In [4]:
lst = [['Alice', 25], ['Bob', 30]]
df = pd.DataFrame(lst, columns=['Name', 'Age'])

In [5]:
df

    Name  Age
0  Alice   25
1    Bob   30

In [6]:
df.head()  	
df.tail()  	
df.info()  	
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [7]:
df['Name']
df[['Name', 'Age']]

    Name  Age
0  Alice   25
1    Bob   30

In [8]:
df.loc[0]
df.iloc[1]

Name    Bob
Age      30
Name: 1, dtype: object

In [9]:
df[df['Age'] > 25]  # Rows where Age > 25

  Name  Age
1  Bob   30

In [ ]:
['Gender']df = ['F', 'M']  # Add new column
df.drop('Age', axis=1, inplace=True)  # Remove column

In [12]:
df

    Name  Age
0  Alice   25
1    Bob   30

In [13]:
df.isnull()
df.dropna()
df.fillna(0)

    Name  Age
0  Alice   25
1    Bob   30

In [ ]:
df.groupby('Gender')['Age'].mean()

In [15]:
df

    Name  Age
0  Alice   25
1    Bob   30

In [ ]:
pd.merge(df1, df2, on='key')

In [18]:
df

    Name  Age
0  Alice   25
1    Bob   30

In [ ]:
df1.join(df2)

In [19]:
df

    Name  Age
0  Alice   25
1    Bob   30

In [ ]:
df = pd.read_csv('data.csv')

In [20]:
df

    Name  Age
0  Alice   25
1    Bob   30

In [ ]:
df.to_csv('output.csv', index=False)

In [21]:
df

    Name  Age
0  Alice   25
1    Bob   30

In [ ]:
df['Age'].apply(lambda x: x + 1)
df['Name'].unique()
df['Age'].value_counts()

In [22]:
df

    Name  Age
0  Alice   25
1    Bob   30